export default {
    LOGIN: "LOGIN",
    LOGOUT: "LOGOUT",
    REGISTER1: "REGISTER1",
    REGISTER2: "REGISTER2",
    CLEAR_REDUX_STATE:"CLEAR_REDUX_STATE",
    LIST_COMMUNITY: "LIST_COMMUNITY",
    CREATE_COMMUNITY_STEP: "CREATE_COMMUNITY_STEP",
    NEWCOMMUNITY: "NEWCOMMUNITY",
    VERIFYURL: "VERIFYURL",
    BOOKING: "BOOKING",
    VEHICLE: "VEHICLE",
    UPLOAD: "UPLOAD",
    YARD: "YARD",
    UPLOAD_IMAGES: "UPLOAD_IMAGES",
    CLEAR_UPLOAD_IMAGES: "CLEAR_UPLOAD_IMAGES",
    TERMINALS: "TERMINALS"
}